# Generated by Django 4.0.5 on 2022-06-20 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=1000)),
                ('vote_id', models.IntegerField()),
                ('group_id', models.IntegerField()),
                ('create_time', models.DateTimeField()),
            ],
        ),
    ]
